# Generated by Django 4.2.10 on 2024-12-14 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0003_manuscript_editor"),
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("sex", models.CharField(max_length=255)),
                ("race", models.CharField(max_length=255)),
                ("education", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer", models.CharField(max_length=255)),
                ("online", models.BooleanField(default=True)),
                ("location", models.CharField(max_length=255)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="manuscript.manuscript",
                    ),
                ),
            ],
        ),
    ]
