# Generated by Django 4.2.10 on 2024-12-12 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manuscript", "0002_manuscript_synopsis"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="editor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editing",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
